const packetType = {
    MOVE: 'MOVE',
    DIRECTION: 'DIRECTION',
    CHANGE_VELOCITY: 'CHANGE_VELOCITY',
    NEW_PLAYER: 'NEW_PLAYER',
    PLAYER_OUT: 'PLAYER_OUT',
    REPLICATION_DATA: 'REPLICATION_DATA',
};